accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),

]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

from receipts.views import(ReceiptListView,ReceiptCreateView



)
urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("home"))
    ),

]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path("accounts/", AccountListView.as_view(), name="account"),
    path("accounts/create/", AccountCreateView.as_view(), name="create_account")

]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings
USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL, related_name="categories", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class Account(models.Model):
    name = models.CharField(max_length=100, null=True)
    number = models.CharField(max_length=20, null=True)
    owner = models.ForeignKey(USER_MODEL, related_name="accounts", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(null=True)
    purchaser = models.ForeignKey(USER_MODEL, related_name='receipts', on_delete=models.CASCADE, null=True)
    category = models.ForeignKey("ExpenseCategory", related_name="receipts", on_delete=models.CASCADE)
    account = models.ForeignKey('Account', related_name='receipts', on_delete=models.CASCADE, null=True)


    def __str__(self):
        return str(self.vendor) + " " + str(self.total) + " "+ str(self.account)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User
from django.contrib.auth import login

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from receipts.models import ExpenseCategory
from receipts.models import Receipt
from receipts.models import Account
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("/receipts/")

class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/expenses.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts.html"


def get_queryset(self):
    return Account.objects.filter(owner=self.request.user)

class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/createcategory.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")

    
class AccountCreateView(CreateView):
    model = Account
    template_name = "receipts/createaccount.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account")

accounts/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>

</body>
</html>

receipts/templates/receipts/accounts.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <main>
        <h1>My Accounts</h1>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Number</th>
              <th>Number of receipts</th>
            </tr>
          </thead>
          <tbody>
            {% for account in account_list %}
            <tr>
              <td>{{ account.name }}</td>
              <td>{{ account.number }}</td>
              <td>{{account|length }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </main>
</body>
</html>

receipts/templates/receipts/create.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post">
              {{ form.as_p}}
              <button type="submit">Create</button>
            </form>
          </div>
    </main>

</body>
</html>

receipts/templates/receipts/createaccount.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="post">
                {% csrf_token %} {{ form.as_p}}
                <button type="submit">Create</button>

        </div>
    </main>

</body>
</html>

receipts/templates/receipts/createcategory.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="post">
              {% csrf_token %} {{ form.as_p}}
              <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>
</html>

receipts/templates/receipts/expenses.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <main>
        <a href="{% url 'list_categories' %}">List</a>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for expense in expensecategory_list %}
    <tr>
      <td>{{ expense.name }}</td>
      <td>{{expense.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div>
  <li>
    <a href="{% url 'create_category' %}">Create</a>
  </li>
</div>
    </main>

</body>
</html>

receipts/templates/receipts/list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <main>
        <h1>My Receipts</h1>
                <table>
                    <thead>
                        <tr>
                            <th>Vendors</th>
                            <th>Total</th>
                            <th>Tax</th>
                            <th>Date</th>
                            <th>Category</th>
                            <th>Account</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for receipt in receipt_list%}
                        <tr>
                            <td>{{receipt.vendor}}</td>
                            <td>{{receipt.total}}</td>
                            <td>{{receipt.tax}}</td>
                            <td>{{receipt.date|date:'m-d-Y' }}</td>
                            <td>{{receipt.category}}</td>
                            <td>{{receipt.account}}</td>
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
    </main>

</body>
</html>